name: "Terraform Azure deployment"

on:
  workflow_call:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_VAR_location: ${{ vars.AZURE_LOCATION }}

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    environment: azure-production
    concurrency: azure-production
    defaults:
      run:
        shell: bash
        working-directory: ./.terraform/azure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Create Backend configuration
        run: |
          echo 'container_name = "terraform-files"' >> config.azurerm.tfbackend
          echo 'key = "terraform.tfstate"' >> config.azurerm.tfbackend
          echo 'resource_group_name = "terraform-resource-group"' >> config.azurerm.tfbackend
          echo 'storage_account_name = "actionsterraformstorage"' >> config.azurerm.tfbackend
          echo 'use_oidc = true' >> config.azurerm.tfbackend

      - name: Terraform Init
        run: terraform init -backend-config=config.azurerm.tfbackend
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -input=false -out=azuretfplan
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: azuretfplan
          path: ./.terraform/azure/azuretfplan

  terraform-apply:
    name: "Terraform Apply"
    needs: [ terraform-plan ]
    runs-on: ubuntu-latest
    environment: azure-production
    concurrency: azure-production
    defaults:
      run:
        shell: bash
        working-directory: ./.terraform/azure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Create Backend configuration
        run: |
          echo 'container_name = "terraform-files"' >> config.azurerm.tfbackend
          echo 'key = "terraform.tfstate"' >> config.azurerm.tfbackend
          echo 'resource_group_name = "terraform-resource-group"' >> config.azurerm.tfbackend
          echo 'storage_account_name = "actionsterraformstorage"' >> config.azurerm.tfbackend
          echo 'use_oidc = true' >> config.azurerm.tfbackend

      - name: Terraform Init
        run: terraform init -backend-config=config.azurerm.tfbackend
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: azuretfplan
          path: ./.terraform/azure
      - name: Terraform Apply
        run: terraform apply -auto-approve azuretfplan
