name: "Terraform GCP deployment"

on:
  workflow_call:

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
  TF_VAR_region: ${{ vars.GCP_REGION }}

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    environment: gcp-production
    concurrency: gcp-production
    defaults:
      run:
        shell: bash
        working-directory: ./.terraform/gcp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Create Backend configuration
        run: |
          echo 'bucket = "actions-bucket-terraform-files"' >> config.gcs.tfbackend
          echo 'prefix = "terraform/state"' >> config.gcs.tfbackend

      - name: Terraform Init
        run: terraform init -backend-config=config.gcs.tfbackend
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -input=false -out=gcptfplan
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: gcptfplan
          path: ./.terraform/gcp/gcptfplan
          retention-days: 7

  terraform-apply:
    name: "Terraform Apply"
    needs: [ terraform-plan ]
    runs-on: ubuntu-latest
    environment: gcp-production
    concurrency: gcp-production
    defaults:
      run:
        shell: bash
        working-directory: ./.terraform/gcp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Create Backend configuration
        run: |
          echo 'bucket = "actions-bucket-terraform-files"' >> config.gcs.tfbackend
          echo 'prefix = "terraform/state"' >> config.gcs.tfbackend

      - name: Terraform Init
        run: terraform init -backend-config=config.gcs.tfbackend
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: gcptfplan
          path: ./.terraform/gcp
      - name: Terraform Apply
        run: terraform apply -auto-approve gcptfplan
