name: "Terraform Deployment"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        options:
          - Production

jobs:
  aws-terraform:
    name: "AWS Deployment"
    uses: ./.github/workflows/aws-terraform.yml
    permissions:
      contents: read
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
  azure-terraform:
    name: "Azure Deployment"
    uses: ./.github/workflows/azure-terraform.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
  gcp-terraform:
    name: "GCP Deployment"
    uses: ./.github/workflows/gcp-terraform.yml
    permissions:
      contents: read
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
  ansible-deployment:
    name: "Ansible Deployment Trigger"
    needs: [ aws-terraform, azure-terraform, gcp-terraform ]
    uses: ./.github/workflows/trigger-ansible.yml
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
