name: 'Terraform GCP deployment'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  TF_VAR_project-id: ${{ vars.GCP_PROJECT_ID }}
  TF_VAR_region: ${{ vars.GCP_REGION }}
  TF_VAR_tf-state-bucket-id: ${{ vars.GCP_TF_STATE_BUCKET_ID }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./.terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan -input=false
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
